/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex("clients").del();
  await knex("clients").insert([
    {
      parent_first_name: "John",
      parent_last_name: "Doe",
      parent_phone: "123-456-7890",
      parent_email: "john.doe@example.com",
      child_first_name: "Jane",
      child_grade: "Grade 5",
      subjects_interested: "Coding, Math",
      city: "Toronto",
      postal_code: "M5V 1A1",
      additional_notes: "",
      status: "Form Filled Out",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Dan",
      parent_last_name: "Gutin",
      parent_phone: "647-123-1234",
      parent_email: "dan.g@gmail.com",
      child_first_name: "Leah",
      child_grade: "Grade 1",
      subjects_interested: "English, Coding, Math, Science",
      city: "Aurora",
      postal_code: "M5V 1A1",
      additional_notes: "",
      status: "Form Filled Out",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Sarah",
      parent_last_name: "Connor",
      parent_phone: "416-987-6543",
      parent_email: "sarah.connor@gmail.com",
      child_first_name: "Kyle",
      child_grade: "Grade 3",
      subjects_interested: "Math, Science",
      city: "Mississauga",
      postal_code: "L5B 4C3",
      additional_notes: "Prefers in-person sessions.",
      status: "Trial Lesson Booked",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Emily",
      parent_last_name: "Rogers",
      parent_phone: "905-234-5678",
      parent_email: "emily.rogers@hotmail.com",
      child_first_name: "Sophie",
      child_grade: "Grade 2",
      subjects_interested: "English, Science",
      city: "Brampton",
      postal_code: "L6Y 5H7",
      additional_notes: "Looking for weekend sessions.",
      status: "Form Filled Out",
      how_did_you_hear: "Facebook",
    },
    {
      parent_first_name: "Michael",
      parent_last_name: "Smith",
      parent_phone: "647-789-1234",
      parent_email: "michael.smith@yahoo.com",
      child_first_name: "Jack",
      child_grade: "Grade 6",
      subjects_interested: "Coding, Math",
      city: "Toronto",
      postal_code: "M6P 4C1",
      additional_notes: "Needs help with Python basics.",
      status: "Contacted",
      how_did_you_hear: "Instagram",
    },
    {
      parent_first_name: "Linda",
      parent_last_name: "Taylor",
      parent_phone: "905-345-6789",
      parent_email: "linda.taylor@gmail.com",
      child_first_name: "Ella",
      child_grade: "Grade 4",
      subjects_interested: "Math, Coding",
      city: "Richmond Hill",
      postal_code: "L4B 3N6",
      additional_notes: "",
      status: "Trial Lesson Booked",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Chris",
      parent_last_name: "Brown",
      parent_phone: "905-111-2222",
      parent_email: "chris.brown@gmail.com",
      child_first_name: "Olivia",
      child_grade: "Grade 7",
      subjects_interested: "Science, English",
      city: "Markham",
      postal_code: "L3R 2S1",
      additional_notes: "Prefers online lessons.",
      status: "Form Filled Out",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Daniel",
      parent_last_name: "Lee",
      parent_phone: "416-555-6666",
      parent_email: "daniel.lee@gmail.com",
      child_first_name: "Lucas",
      child_grade: "Grade 8",
      subjects_interested: "Coding, Math",
      city: "Scarborough",
      postal_code: "M1C 1B8",
      additional_notes: "Needs help preparing for coding competition.",
      status: "Contacted",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Amanda",
      parent_last_name: "Jones",
      parent_phone: "416-222-3333",
      parent_email: "amanda.jones@gmail.com",
      child_first_name: "Grace",
      child_grade: "Grade 5",
      subjects_interested: "Math, English",
      city: "Etobicoke",
      postal_code: "M9B 4V1",
      additional_notes: "Looking for after-school sessions.",
      status: "Form Filled Out",
      how_did_you_hear: "Facebook",
    },
    {
      parent_first_name: "David",
      parent_last_name: "Nguyen",
      parent_phone: "647-999-8888",
      parent_email: "david.nguyen@gmail.com",
      child_first_name: "Ethan",
      child_grade: "Grade 4",
      subjects_interested: "Science, Coding",
      city: "Vaughan",
      postal_code: "L4H 3M9",
      additional_notes: "Interested in group classes.",
      status: "Trial Lesson Booked",
      how_did_you_hear: "Instagram",
    },
  ]);
}
