/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex("clients").del();
  await knex("clients").insert([
    {
      parent_first_name: "Kenneth",
      parent_last_name: "Nelson",
      parent_phone: "480-300-0488",
      parent_email: "kenneth.nelson@example.com",
      child_first_name: "Max",
      child_grade: "Grade 8",
      subjects_interested: "English, Coding, Science, Math",
      city: "Hamilton",
      postal_code: "77830",
      additional_notes: "Collection will able card fly really.",
      status: "Trial Completed",
      how_did_you_hear: "Social Media",
    },
    {
      parent_first_name: "James",
      parent_last_name: "Long",
      parent_phone: "738-148-0098",
      parent_email: "james.long@example.com",
      child_first_name: "Mario",
      child_grade: "Grade 4",
      subjects_interested: "Math, Coding, Science",
      city: "Brampton",
      postal_code: "84246",
      additional_notes: "May how direction community.",
      status: "Trial Completed",
      how_did_you_hear: "Online Ad",
    },
    {
      parent_first_name: "Donald",
      parent_last_name: "Cohen",
      parent_phone: "114-168-7954",
      parent_email: "donald.cohen@example.com",
      child_first_name: "Richard",
      child_grade: "Grade 8",
      subjects_interested: "English, Coding",
      city: "Toronto",
      postal_code: "76831",
      additional_notes:
        "Media election statement behavior consider air without.",
      status: "Invoice Sent",
      how_did_you_hear: "Online Ad",
    },
    {
      parent_first_name: "Monique",
      parent_last_name: "Miller",
      parent_phone: "434-795-3528",
      parent_email: "monique.miller@example.com",
      child_first_name: "Alexander",
      child_grade: "Grade 5",
      subjects_interested: "Coding",
      city: "Toronto",
      postal_code: "30253",
      additional_notes:
        "Call action reality traditional property everything partner.",
      status: "Can't Reach",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Breanna",
      parent_last_name: "Ward",
      parent_phone: "021-701-0664",
      parent_email: "breanna.ward@example.com",
      child_first_name: "Madison",
      child_grade: "Grade 5",
      subjects_interested: "Math, Science, English",
      city: "London",
      postal_code: "15129",
      additional_notes: "Forward clearly think traditional.",
      status: "Not a Fit",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Jesse",
      parent_last_name: "Evans",
      parent_phone: "578-511-8270",
      parent_email: "jesse.evans@example.com",
      child_first_name: "Heather",
      child_grade: "Grade 2",
      subjects_interested: "Science, English",
      city: "Ottawa",
      postal_code: "20502",
      additional_notes: "That energy hold.",
      status: "Can't Reach",
      how_did_you_hear: "Friend Referral",
    },
    {
      parent_first_name: "Ricky",
      parent_last_name: "Vaughn",
      parent_phone: "560-653-7605",
      parent_email: "ricky.vaughn@example.com",
      child_first_name: "Stacy",
      child_grade: "Grade 1",
      subjects_interested: "Coding, Science, English, Math",
      city: "Hamilton",
      postal_code: "61535",
      additional_notes: "Her small reduce thousand keep.",
      status: "Invoice Sent",
      how_did_you_hear: "Online Ad",
    },
    {
      parent_first_name: "Joseph",
      parent_last_name: "Hernandez",
      parent_phone: "163-582-7453",
      parent_email: "joseph.hernandez@example.com",
      child_first_name: "Tamara",
      child_grade: "Grade 4",
      subjects_interested: "English, Coding, Math, Science",
      city: "Brampton",
      postal_code: "65244",
      additional_notes:
        "Production whatever difficult though former discussion.",
      status: "Not a Fit",
      how_did_you_hear: "Online Ad",
    },
    {
      parent_first_name: "April",
      parent_last_name: "Wilson",
      parent_phone: "074-526-4410",
      parent_email: "april.wilson@example.com",
      child_first_name: "Deborah",
      child_grade: "Grade 5",
      subjects_interested: "Coding, English, Science",
      city: "Markham",
      postal_code: "36932",
      additional_notes: "Involve run single our he.",
      status: "Invoice Sent",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Joel",
      parent_last_name: "Baldwin",
      parent_phone: "424-552-2545",
      parent_email: "joel.baldwin@example.com",
      child_first_name: "Sharon",
      child_grade: "Grade 6",
      subjects_interested: "English, Coding, Math",
      city: "Windsor",
      postal_code: "57910",
      additional_notes: "Heart beat security difference difficult probably.",
      status: "Not a Fit",
      how_did_you_hear: "Social Media",
    },
    {
      parent_first_name: "Jacob",
      parent_last_name: "Bartlett",
      parent_phone: "556-795-2938",
      parent_email: "jacob.bartlett@example.com",
      child_first_name: "Jacqueline",
      child_grade: "Grade 8",
      subjects_interested: "Coding, Math, English, Science",
      city: "Markham",
      postal_code: "72382",
      additional_notes: "Study leg professional area blue hope.",
      status: "No Show",
      how_did_you_hear: "Social Media",
    },
    {
      parent_first_name: "Breanna",
      parent_last_name: "Lopez",
      parent_phone: "325-655-8932",
      parent_email: "breanna.lopez@example.com",
      child_first_name: "Danielle",
      child_grade: "Grade 6",
      subjects_interested: "English, Coding, Math, Science",
      city: "Markham",
      postal_code: "54705",
      additional_notes:
        "Either statement attorney land exist civil listen catch.",
      status: "Not a Fit",
      how_did_you_hear: "Online Ad",
    },
    {
      parent_first_name: "Diana",
      parent_last_name: "Romero",
      parent_phone: "761-290-9555",
      parent_email: "diana.romero@example.com",
      child_first_name: "Kristy",
      child_grade: "Grade 3",
      subjects_interested: "Science, Math, Coding",
      city: "Ottawa",
      postal_code: "62243",
      additional_notes: "Western sell study he court.",
      status: "Not a Fit",
      how_did_you_hear: "Friend Referral",
    },
    {
      parent_first_name: "Hayden",
      parent_last_name: "Sampson",
      parent_phone: "704-156-1484",
      parent_email: "hayden.sampson@example.com",
      child_first_name: "Susan",
      child_grade: "Grade 7",
      subjects_interested: "Coding, Science, English",
      city: "Ottawa",
      postal_code: "34462",
      additional_notes: "Case begin audience whose after.",
      status: "Invoice Sent",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Ryan",
      parent_last_name: "Cruz",
      parent_phone: "250-173-7433",
      parent_email: "ryan.cruz@example.com",
      child_first_name: "Stephen",
      child_grade: "Grade 4",
      subjects_interested: "Math",
      city: "Brampton",
      postal_code: "64121",
      additional_notes: "Nearly record tax sport unit.",
      status: "Trial Completed",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Thomas",
      parent_last_name: "Lee",
      parent_phone: "289-291-8591",
      parent_email: "thomas.lee@example.com",
      child_first_name: "Cynthia",
      child_grade: "Grade 5",
      subjects_interested: "Science, English, Coding, Math",
      city: "Ottawa",
      postal_code: "80082",
      additional_notes: "Even maintain Democrat still.",
      status: "Trial Scheduled",
      how_did_you_hear: "Online Ad",
    },
    {
      parent_first_name: "Hayden",
      parent_last_name: "Sampson",
      parent_phone: "704-156-1484",
      parent_email: "hayden.sampson@example.com",
      child_first_name: "Susan",
      child_grade: "Grade 7",
      subjects_interested: "Coding, Science, English",
      city: "Ottawa",
      postal_code: "34462",
      additional_notes: "Case begin audience whose after.",
      status: "Invoice Sent",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Ryan",
      parent_last_name: "Cruz",
      parent_phone: "250-173-7433",
      parent_email: "ryan.cruz@example.com",
      child_first_name: "Stephen",
      child_grade: "Grade 4",
      subjects_interested: "Math",
      city: "Brampton",
      postal_code: "64121",
      additional_notes: "Nearly record tax sport unit.",
      status: "Trial Completed",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Thomas",
      parent_last_name: "Lee",
      parent_phone: "289-291-8591",
      parent_email: "thomas.lee@example.com",
      child_first_name: "Cynthia",
      child_grade: "Grade 5",
      subjects_interested: "Science, English, Coding, Math",
      city: "Ottawa",
      postal_code: "80082",
      additional_notes: "Even maintain Democrat still.",
      status: "Trial Scheduled",
      how_did_you_hear: "Online Ad",
    },
    {
      parent_first_name: "Amanda",
      parent_last_name: "Smith",
      parent_phone: "123-456-7890",
      parent_email: "amanda.smith@example.com",
      child_first_name: "Lucas",
      child_grade: "Grade 3",
      subjects_interested: "Math",
      city: "Mississauga",
      postal_code: "N5Z 2P8",
      additional_notes: "Interested in group classes.",
      status: "New Lead",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "John",
      parent_last_name: "Doe",
      parent_phone: "987-654-3210",
      parent_email: "john.doe@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 6",
      subjects_interested: "Science, Math",
      city: "Toronto",
      postal_code: "M4B 1B3",
      additional_notes: "Needs evening sessions.",
      status: "Can't Reach",
      how_did_you_hear: "Social Media",
    },
    {
      parent_first_name: "Sarah",
      parent_last_name: "Brown",
      parent_phone: "345-678-9012",
      parent_email: "sarah.brown@gmail.com",
      child_first_name: "Ella",
      child_grade: "Grade 2",
      subjects_interested: "English",
      city: "Hamilton",
      postal_code: "L8P 1B2",
      additional_notes: "Prefers one-on-one tutoring.",
      status: "Not a Fit",
      how_did_you_hear: "Online Search",
    },
    {
      parent_first_name: "Liam",
      parent_last_name: "Walker",
      parent_phone: "234-567-8901",
      parent_email: "liam.walker@outlook.com",
      child_first_name: "Ethan",
      child_grade: "Grade 7",
      subjects_interested: "Math, Coding",
      city: "Ottawa",
      postal_code: "K1A 0B1",
      additional_notes: "Looking for immediate start.",
      status: "Invoice Sent",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Olivia",
      parent_last_name: "Taylor",
      parent_phone: "876-543-2109",
      parent_email: "olivia.taylor@yahoo.com",
      child_first_name: "Chloe",
      child_grade: "Grade 4",
      subjects_interested: "Science, Math, English",
      city: "Brampton",
      postal_code: "L6T 3R1",
      additional_notes: "Flexible with scheduling.",
      status: "Enrolled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Emma",
      parent_last_name: "Clark",
      parent_phone: "564-738-2019",
      parent_email: "emma.clark@gmail.com",
      child_first_name: "Noah",
      child_grade: "Grade 5",
      subjects_interested: "English",
      city: "Mississauga",
      postal_code: "N5Z 2P8",
      additional_notes: "Interested in group classes.",
      status: "Trial Scheduled",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Ethan",
      parent_last_name: "Hill",
      parent_phone: "908-765-4321",
      parent_email: "ethan.hill@example.com",
      child_first_name: "Ava",
      child_grade: "Grade 1",
      subjects_interested: "Coding",
      city: "Toronto",
      postal_code: "M4B 1B3",
      additional_notes: "Needs weekend sessions.",
      status: "Trial Completed",
      how_did_you_hear: "Social Media",
    },
    {
      parent_first_name: "Sophia",
      parent_last_name: "Johnson",
      parent_phone: "234-987-6543",
      parent_email: "sophia.johnson@gmail.com",
      child_first_name: "Mason",
      child_grade: "Grade 8",
      subjects_interested: "Science, Coding",
      city: "Hamilton",
      postal_code: "L8P 1B2",
      additional_notes: "Prefers evening tutoring.",
      status: "No Show",
      how_did_you_hear: "Online Search",
    },
    {
      parent_first_name: "John",
      parent_last_name: "Evans",
      parent_phone: "234-917-6543",
      parent_email: "john.evans@gmail.com",
      child_first_name: "Samuel",
      child_grade: "Grade 3",
      subjects_interested: "Science, Coding",
      city: "Hamilton",
      postal_code: "L8P 1F2",
      additional_notes: "Prefers weekend tutoring.",
      status: "Enrolled",
      how_did_you_hear: "Online Search",
    },
    {
      parent_first_name: "Pasha",
      parent_last_name: "Samuels",
      parent_phone: "564-917-6543",
      parent_email: "Pasha.Samuels@gmail.com",
      child_first_name: "Justin",
      child_grade: "Grade 4",
      subjects_interested: "English, Coding",
      city: "Vaughan",
      postal_code: "L8P 3F2",
      additional_notes: "Prefers weekday tutoring.",
      status: "New Lead",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Michal",
      parent_last_name: "Manoah",
      parent_phone: "564-123-6543",
      parent_email: "Michal.Manoah@gmail.com",
      child_first_name: "Nikki",
      child_grade: "Grade 2",
      subjects_interested: "English",
      city: "Maple",
      postal_code: "L1P 3F2",
      additional_notes: "Prefers weekday tutoring.",
      status: "Enrolled",
      how_did_you_hear: "Facebook",
    },
    {
      parent_first_name: "Isabella",
      parent_last_name: "Morris",
      parent_phone: "416-123-4567",
      parent_email: "isabella.morris@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 6",
      subjects_interested: "Math, Science",
      city: "Toronto",
      postal_code: "M1B 4X3",
      additional_notes: "Needs help preparing for a science fair.",
      status: "Invoice Sent",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Michael",
      parent_last_name: "Patterson",
      parent_phone: "613-456-7890",
      parent_email: "michael.patterson@gmail.com",
      child_first_name: "Liam",
      child_grade: "Grade 8",
      subjects_interested: "Coding, Math",
      city: "Ottawa",
      postal_code: "K1A 1A1",
      additional_notes: "Prefers weekend sessions.",
      status: "Trial Completed",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Emma",
      parent_last_name: "Gray",
      parent_phone: "519-234-5678",
      parent_email: "emma.gray@hotmail.com",
      child_first_name: "Mason",
      child_grade: "Grade 4",
      subjects_interested: "English, Science",
      city: "London",
      postal_code: "N6A 3L6",
      additional_notes: "Needs improvement in reading comprehension.",
      status: "Can't Reach",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Sophia",
      parent_last_name: "Brooks",
      parent_phone: "780-345-6789",
      parent_email: "sophia.brooks@gmail.com",
      child_first_name: "Ella",
      child_grade: "Grade 2",
      subjects_interested: "Math, English",
      city: "Edmonton",
      postal_code: "T5J 1Z2",
      additional_notes: "Looking for a patient tutor.",
      status: "Not a Fit",
      how_did_you_hear: "Facebook Ad",
    },
    {
      parent_first_name: "James",
      parent_last_name: "Campbell",
      parent_phone: "204-456-7890",
      parent_email: "james.campbell@example.com",
      child_first_name: "Ava",
      child_grade: "Grade 7",
      subjects_interested: "Math, Coding",
      city: "Winnipeg",
      postal_code: "R3C 4T3",
      additional_notes: "Interested in group classes.",
      status: "New Lead",
      how_did_you_hear: "Online Ad",
    },
    {
      parent_first_name: "Olivia",
      parent_last_name: "Stewart",
      parent_phone: "905-678-1234",
      parent_email: "olivia.stewart@example.com",
      child_first_name: "Noah",
      child_grade: "Grade 3",
      subjects_interested: "Science",
      city: "Brampton",
      postal_code: "L6X 4W3",
      additional_notes: "Prefers one-on-one tutoring.",
      status: "No Show",
      how_did_you_hear: "Instagram",
    },
    {
      parent_first_name: "Benjamin",
      parent_last_name: "Turner",
      parent_phone: "604-789-4567",
      parent_email: "benjamin.turner@gmail.com",
      child_first_name: "Emily",
      child_grade: "Grade 5",
      subjects_interested: "English, Coding",
      city: "Vancouver",
      postal_code: "V6B 5K3",
      additional_notes: "Needs evening sessions.",
      status: "Enrolled",
      how_did_you_hear: "Friend",
    },
    {
      parent_first_name: "Charlotte",
      parent_last_name: "Edwards",
      parent_phone: "403-890-5678",
      parent_email: "charlotte.edwards@hotmail.com",
      child_first_name: "Logan",
      child_grade: "Grade 6",
      subjects_interested: "Math, Science",
      city: "Calgary",
      postal_code: "T2G 4Z5",
      additional_notes: "Available only on weekdays.",
      status: "Trial Scheduled",
      how_did_you_hear: "Search Engine",
    },
    {
      parent_first_name: "William",
      parent_last_name: "Carter",
      parent_phone: "647-901-2345",
      parent_email: "william.carter@example.com",
      child_first_name: "Amelia",
      child_grade: "Grade 1",
      subjects_interested: "Math",
      city: "Toronto",
      postal_code: "M5V 2T6",
      additional_notes: "Looking for a playful approach to teaching.",
      status: "Enrolled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Mia",
      parent_last_name: "Hughes",
      parent_phone: "289-567-8901",
      parent_email: "mia.hughes@gmail.com",
      child_first_name: "Jackson",
      child_grade: "Grade 3",
      subjects_interested: "Science, English",
      city: "Mississauga",
      postal_code: "L5B 2T4",
      additional_notes: "Needs help with projects.",
      status: "Invoice Sent",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Logan",
      parent_last_name: "Howard",
      parent_phone: "613-234-5678",
      parent_email: "logan.howard@example.com",
      child_first_name: "Aria",
      child_grade: "Grade 2",
      subjects_interested: "English",
      city: "Kingston",
      postal_code: "K7L 2X4",
      additional_notes: "Needs to build confidence in writing.",
      status: "New Lead",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Avery",
      parent_last_name: "Young",
      parent_phone: "514-345-6789",
      parent_email: "avery.young@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 8",
      subjects_interested: "Coding",
      city: "Montreal",
      postal_code: "H3A 1B2",
      additional_notes: "Interested in advanced coding classes.",
      status: "Trial Completed",
      how_did_you_hear: "Facebook",
    },
    {
      parent_first_name: "Lily",
      parent_last_name: "Anderson",
      parent_phone: "780-678-1234",
      parent_email: "lily.anderson@gmail.com",
      child_first_name: "Isabella",
      child_grade: "Grade 7",
      subjects_interested: "Math, English",
      city: "Edmonton",
      postal_code: "T5K 3G4",
      additional_notes: "Prefers early morning sessions.",
      status: "Can't Reach",
      how_did_you_hear: "Friend",
    },
    {
      parent_first_name: "Ella",
      parent_last_name: "Moore",
      parent_phone: "902-789-2345",
      parent_email: "ella.moore@hotmail.com",
      child_first_name: "Benjamin",
      child_grade: "Grade 4",
      subjects_interested: "Science",
      city: "Halifax",
      postal_code: "B3H 4R5",
      additional_notes: "Wants to focus on exam preparation.",
      status: "Enrolled",
      how_did_you_hear: "Instagram",
    },
    {
      parent_first_name: "Noah",
      parent_last_name: "Phillips",
      parent_phone: "807-234-5678",
      parent_email: "noah.phillips@example.com",
      child_first_name: "Oliver",
      child_grade: "Grade 6",
      subjects_interested: "Math, Coding",
      city: "Thunder Bay",
      postal_code: "P7E 3V4",
      additional_notes: "Available only in the evenings.",
      status: "No Show",
      how_did_you_hear: "Search Engine",
    },
    {
      parent_first_name: "Sophia",
      parent_last_name: "Adams",
      parent_phone: "647-555-1234",
      parent_email: "sophia.adams@example.com",
      child_first_name: "Lucas",
      child_grade: "Grade 2",
      subjects_interested: "English, Math",
      city: "Toronto",
      postal_code: "M4C 1B5",
      additional_notes: "Needs foundational skills.",
      status: "Invoice Sent",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Ethan",
      parent_last_name: "Anderson",
      parent_phone: "613-555-6789",
      parent_email: "ethan.anderson@example.com",
      child_first_name: "Liam",
      child_grade: "Grade 5",
      subjects_interested: "Science, Coding",
      city: "Ottawa",
      postal_code: "K2P 1L4",
      additional_notes: "Wants hands-on experiments.",
      status: "Trial Completed",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Ava",
      parent_last_name: "Baker",
      parent_phone: "905-555-9876",
      parent_email: "ava.baker@example.com",
      child_first_name: "Olivia",
      child_grade: "Grade 7",
      subjects_interested: "Math, Science",
      city: "Mississauga",
      postal_code: "L5R 1B8",
      additional_notes: "Prefers evening sessions.",
      status: "Trial Scheduled",
      how_did_you_hear: "Facebook",
    },
    {
      parent_first_name: "Liam",
      parent_last_name: "Clark",
      parent_phone: "780-555-4321",
      parent_email: "liam.clark@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 3",
      subjects_interested: "English",
      city: "Edmonton",
      postal_code: "T5J 2M3",
      additional_notes: "Needs improvement in grammar.",
      status: "New Lead",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Mia",
      parent_last_name: "Davis",
      parent_phone: "519-555-8765",
      parent_email: "mia.davis@example.com",
      child_first_name: "Noah",
      child_grade: "Grade 4",
      subjects_interested: "Science",
      city: "London",
      postal_code: "N6A 3L6",
      additional_notes: "Interested in group classes.",
      status: "Can't Reach",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "James",
      parent_last_name: "Evans",
      parent_phone: "416-555-1234",
      parent_email: "james.evans@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 1",
      subjects_interested: "Math",
      city: "Toronto",
      postal_code: "M4G 2C3",
      additional_notes: "Prefers weekend sessions.",
      status: "Not a Fit",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Isabella",
      parent_last_name: "Flores",
      parent_phone: "647-555-4321",
      parent_email: "isabella.flores@example.com",
      child_first_name: "Lucas",
      child_grade: "Grade 8",
      subjects_interested: "Coding",
      city: "Toronto",
      postal_code: "M4V 1C8",
      additional_notes: "Wants advanced coding lessons.",
      status: "Invoice Sent",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Oliver",
      parent_last_name: "Garcia",
      parent_phone: "780-555-5678",
      parent_email: "oliver.garcia@example.com",
      child_first_name: "Ava",
      child_grade: "Grade 2",
      subjects_interested: "Math, English",
      city: "Edmonton",
      postal_code: "T5J 3L5",
      additional_notes: "Needs help with homework.",
      status: "Enrolled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Emma",
      parent_last_name: "Harris",
      parent_phone: "905-555-7890",
      parent_email: "emma.harris@example.com",
      child_first_name: "Mason",
      child_grade: "Grade 3",
      subjects_interested: "Science, Coding",
      city: "Brampton",
      postal_code: "L6Y 4T6",
      additional_notes: "Prefers weekday evenings.",
      status: "Trial Scheduled",
      how_did_you_hear: "Facebook Ad",
    },
    {
      parent_first_name: "Charlotte",
      parent_last_name: "Jackson",
      parent_phone: "289-555-3210",
      parent_email: "charlotte.jackson@example.com",
      child_first_name: "Ella",
      child_grade: "Grade 6",
      subjects_interested: "Math, Science",
      city: "Hamilton",
      postal_code: "L8P 3T2",
      additional_notes: "Flexible with scheduling.",
      status: "No Show",
      how_did_you_hear: "Instagram",
    },
    {
      parent_first_name: "Lucas",
      parent_last_name: "King",
      parent_phone: "647-555-9876",
      parent_email: "lucas.king@example.com",
      child_first_name: "Emily",
      child_grade: "Grade 7",
      subjects_interested: "English",
      city: "Toronto",
      postal_code: "M4C 1B5",
      additional_notes: "Looking for test preparation.",
      status: "Enrolled",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Mason",
      parent_last_name: "Lewis",
      parent_phone: "905-555-4567",
      parent_email: "mason.lewis@example.com",
      child_first_name: "Avery",
      child_grade: "Grade 5",
      subjects_interested: "Science, Coding",
      city: "Mississauga",
      postal_code: "L5V 1B8",
      additional_notes: "Prefers one-on-one tutoring.",
      status: "Invoice Sent",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Ella",
      parent_last_name: "Martinez",
      parent_phone: "613-555-8765",
      parent_email: "ella.martinez@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 3",
      subjects_interested: "Math, English",
      city: "Ottawa",
      postal_code: "K1P 1L4",
      additional_notes: "Wants foundational skills.",
      status: "New Lead",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Noah",
      parent_last_name: "Nelson",
      parent_phone: "780-555-5678",
      parent_email: "noah.nelson@example.com",
      child_first_name: "Olivia",
      child_grade: "Grade 2",
      subjects_interested: "Science, Math",
      city: "Edmonton",
      postal_code: "T5J 3L5",
      additional_notes: "Needs help with projects.",
      status: "Can't Reach",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Avery",
      parent_last_name: "Perez",
      parent_phone: "647-555-7890",
      parent_email: "avery.perez@example.com",
      child_first_name: "Liam",
      child_grade: "Grade 4",
      subjects_interested: "English, Coding",
      city: "Toronto",
      postal_code: "M4C 1B5",
      additional_notes: "Interested in creative writing.",
      status: "Not a Fit",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Benjamin",
      parent_last_name: "Roberts",
      parent_phone: "905-555-6543",
      parent_email: "benjamin.roberts@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 8",
      subjects_interested: "Math, Science",
      city: "Brampton",
      postal_code: "L6Y 4T6",
      additional_notes: "Needs help with final exams.",
      status: "Invoice Sent",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Logan",
      parent_last_name: "Scott",
      parent_phone: "905-555-3210",
      parent_email: "logan.scott@example.com",
      child_first_name: "Mia",
      child_grade: "Grade 6",
      subjects_interested: "Science",
      city: "Hamilton",
      postal_code: "L8P 3T2",
      additional_notes: "Flexible with scheduling.",
      status: "Enrolled",
      how_did_you_hear: "Facebook",
    },
    {
      parent_first_name: "Charlotte",
      parent_last_name: "Taylor",
      parent_phone: "905-555-6543",
      parent_email: "charlotte.taylor@example.com",
      child_first_name: "Mason",
      child_grade: "Grade 5",
      subjects_interested: "English",
      city: "Mississauga",
      postal_code: "L5V 1B8",
      additional_notes: "Needs help with essays.",
      status: "Trial Completed",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Emily",
      parent_last_name: "Walker",
      parent_phone: "647-555-7890",
      parent_email: "emily.walker@example.com",
      child_first_name: "Ava",
      child_grade: "Grade 3",
      subjects_interested: "Coding, Math",
      city: "Toronto",
      postal_code: "M4C 1B5",
      additional_notes: "Wants group classes.",
      status: "Trial Scheduled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Liam",
      parent_last_name: "Young",
      parent_phone: "905-555-4321",
      parent_email: "liam.young@example.com",
      child_first_name: "Ella",
      child_grade: "Grade 2",
      subjects_interested: "Math, English",
      city: "Brampton",
      postal_code: "L6Y 4T6",
      additional_notes: "Needs homework support.",
      status: "No Show",
      how_did_you_hear: "Instagram",
    },
    {
      parent_first_name: "Mia",
      parent_last_name: "Williams",
      parent_phone: "647-555-1234",
      parent_email: "mia.williams@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 1",
      subjects_interested: "Math, Science",
      city: "Toronto",
      postal_code: "M4G 2C3",
      additional_notes: "Looking for basic science projects.",
      status: "Enrolled",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Daniel",
      parent_last_name: "Hughes",
      parent_phone: "416-555-7890",
      parent_email: "daniel.hughes@example.com",
      child_first_name: "Ava",
      child_grade: "Grade 6",
      subjects_interested: "Math, Science",
      city: "Toronto",
      postal_code: "M4V 1N2",
      additional_notes: "Looking for test preparation.",
      status: "Invoice Sent",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Emily",
      parent_last_name: "Lopez",
      parent_phone: "905-555-6543",
      parent_email: "emily.lopez@example.com",
      child_first_name: "Liam",
      child_grade: "Grade 7",
      subjects_interested: "Coding, Math",
      city: "Mississauga",
      postal_code: "L5V 2N1",
      additional_notes: "Prefers hands-on lessons.",
      status: "Trial Completed",
      how_did_you_hear: "Facebook",
    },
    {
      parent_first_name: "Lucas",
      parent_last_name: "Anderson",
      parent_phone: "780-555-4321",
      parent_email: "lucas.anderson@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 5",
      subjects_interested: "English",
      city: "Edmonton",
      postal_code: "T5J 1X5",
      additional_notes: "Needs help with reading fluency.",
      status: "New Lead",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Grace",
      parent_last_name: "White",
      parent_phone: "613-555-5678",
      parent_email: "grace.white@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 2",
      subjects_interested: "Math, Science",
      city: "Ottawa",
      postal_code: "K1P 1N3",
      additional_notes: "Prefers evening sessions.",
      status: "Can't Reach",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Oliver",
      parent_last_name: "King",
      parent_phone: "905-555-8765",
      parent_email: "oliver.king@example.com",
      child_first_name: "Noah",
      child_grade: "Grade 8",
      subjects_interested: "Coding, Math",
      city: "Hamilton",
      postal_code: "L8P 1X2",
      additional_notes: "Interested in competitive coding.",
      status: "Trial Scheduled",
      how_did_you_hear: "Instagram",
    },
    {
      parent_first_name: "Mason",
      parent_last_name: "Scott",
      parent_phone: "416-555-3210",
      parent_email: "mason.scott@example.com",
      child_first_name: "Mia",
      child_grade: "Grade 4",
      subjects_interested: "Science, English",
      city: "Toronto",
      postal_code: "M4B 1B4",
      additional_notes: "Looking for small group classes.",
      status: "No Show",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Charlotte",
      parent_last_name: "Evans",
      parent_phone: "647-555-9876",
      parent_email: "charlotte.evans@example.com",
      child_first_name: "Ella",
      child_grade: "Grade 3",
      subjects_interested: "English",
      city: "Brampton",
      postal_code: "L6X 4B1",
      additional_notes: "Needs creative writing support.",
      status: "Enrolled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Avery",
      parent_last_name: "Harris",
      parent_phone: "905-555-7890",
      parent_email: "avery.harris@example.com",
      child_first_name: "Lucas",
      child_grade: "Grade 6",
      subjects_interested: "Math, Coding",
      city: "Mississauga",
      postal_code: "L5M 2N4",
      additional_notes: "Prefers weekend lessons.",
      status: "Invoice Sent",
      how_did_you_hear: "Search Engine",
    },
    {
      parent_first_name: "Isabella",
      parent_last_name: "Walker",
      parent_phone: "204-555-6543",
      parent_email: "isabella.walker@example.com",
      child_first_name: "Liam",
      child_grade: "Grade 5",
      subjects_interested: "Math, Science",
      city: "Winnipeg",
      postal_code: "R3C 1N4",
      additional_notes: "Flexible with scheduling.",
      status: "New Lead",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Sophia",
      parent_last_name: "Lewis",
      parent_phone: "780-555-8765",
      parent_email: "sophia.lewis@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 7",
      subjects_interested: "Math, Science",
      city: "Edmonton",
      postal_code: "T5J 1X3",
      additional_notes: "Needs help with assignments.",
      status: "Trial Completed",
      how_did_you_hear: "Facebook Ad",
    },
    {
      parent_first_name: "Liam",
      parent_last_name: "Adams",
      parent_phone: "416-555-7890",
      parent_email: "liam.adams@example.com",
      child_first_name: "Noah",
      child_grade: "Grade 8",
      subjects_interested: "Science, Coding",
      city: "Toronto",
      postal_code: "M4C 1N2",
      additional_notes: "Wants advanced tutoring.",
      status: "Trial Scheduled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Olivia",
      parent_last_name: "Martinez",
      parent_phone: "905-555-1234",
      parent_email: "olivia.martinez@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 6",
      subjects_interested: "English, Math",
      city: "Brampton",
      postal_code: "L6X 4N3",
      additional_notes: "Prefers one-on-one sessions.",
      status: "Invoice Sent",
      how_did_you_hear: "Instagram",
    },
    {
      parent_first_name: "Benjamin",
      parent_last_name: "Nelson",
      parent_phone: "647-555-6543",
      parent_email: "benjamin.nelson@example.com",
      child_first_name: "Mason",
      child_grade: "Grade 5",
      subjects_interested: "Science",
      city: "Toronto",
      postal_code: "M4V 2N4",
      additional_notes: "Flexible with scheduling.",
      status: "Enrolled",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Charlotte",
      parent_last_name: "Smith",
      parent_phone: "905-555-5678",
      parent_email: "charlotte.smith@example.com",
      child_first_name: "Ella",
      child_grade: "Grade 2",
      subjects_interested: "English, Math",
      city: "Hamilton",
      postal_code: "L8P 1N3",
      additional_notes: "Looking for test prep support.",
      status: "Trial Completed",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Emily",
      parent_last_name: "Moore",
      parent_phone: "416-555-4321",
      parent_email: "emily.moore@example.com",
      child_first_name: "Ava",
      child_grade: "Grade 4",
      subjects_interested: "Science",
      city: "Toronto",
      postal_code: "M4B 1N2",
      additional_notes: "Prefers evening sessions.",
      status: "No Show",
      how_did_you_hear: "Search Engine",
    },
    {
      parent_first_name: "Logan",
      parent_last_name: "Perez",
      parent_phone: "905-555-9876",
      parent_email: "logan.perez@example.com",
      child_first_name: "Lucas",
      child_grade: "Grade 7",
      subjects_interested: "Math, Coding",
      city: "Mississauga",
      postal_code: "L5R 1N3",
      additional_notes: "Looking for group lessons.",
      status: "Enrolled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Liam",
      parent_last_name: "Thompson",
      parent_phone: "647-555-8765",
      parent_email: "liam.thompson@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 5",
      subjects_interested: "English, Science",
      city: "Toronto",
      postal_code: "M4C 2N1",
      additional_notes: "Flexible with scheduling.",
      status: "New Lead",
      how_did_you_hear: "Facebook Ad",
    },
    {
      parent_first_name: "Ava",
      parent_last_name: "Brown",
      parent_phone: "905-555-6543",
      parent_email: "ava.brown@example.com",
      child_first_name: "Noah",
      child_grade: "Grade 8",
      subjects_interested: "Science, Math",
      city: "Brampton",
      postal_code: "L6X 3N4",
      additional_notes: "Looking for advanced lessons.",
      status: "Can't Reach",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Isabella",
      parent_last_name: "Roberts",
      parent_phone: "416-555-3210",
      parent_email: "isabella.roberts@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 6",
      subjects_interested: "Math, Science",
      city: "Toronto",
      postal_code: "M4V 1N3",
      additional_notes: "Prefers evening sessions.",
      status: "Trial Scheduled",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "James",
      parent_last_name: "Carter",
      parent_phone: "905-555-7890",
      parent_email: "james.carter@example.com",
      child_first_name: "Ava",
      child_grade: "Grade 3",
      subjects_interested: "English, Science",
      city: "Mississauga",
      postal_code: "L5M 2N3",
      additional_notes: "Looking for one-on-one lessons.",
      status: "No Show",
      how_did_you_hear: "Facebook",
    },
    {
      parent_first_name: "Oliver",
      parent_last_name: "Bennett",
      parent_phone: "403-555-4321",
      parent_email: "oliver.bennett@example.com",
      child_first_name: "Liam",
      child_grade: "Grade 6",
      subjects_interested: "Math, Coding",
      city: "Calgary",
      postal_code: "T2P 1B2",
      additional_notes: "Interested in small group classes.",
      status: "Invoice Sent",
      how_did_you_hear: "Search Engine",
    },
    {
      parent_first_name: "Emma",
      parent_last_name: "Henderson",
      parent_phone: "514-555-7890",
      parent_email: "emma.henderson@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 5",
      subjects_interested: "English, Math",
      city: "Montreal",
      postal_code: "H2X 3L4",
      additional_notes: "Needs help with grammar and algebra.",
      status: "Trial Completed",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Charlotte",
      parent_last_name: "Sanders",
      parent_phone: "604-555-1234",
      parent_email: "charlotte.sanders@example.com",
      child_first_name: "Ella",
      child_grade: "Grade 3",
      subjects_interested: "Science, English",
      city: "Vancouver",
      postal_code: "V6B 2L1",
      additional_notes: "Prefers weekend sessions.",
      status: "New Lead",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Lucas",
      parent_last_name: "Reed",
      parent_phone: "613-555-9876",
      parent_email: "lucas.reed@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 2",
      subjects_interested: "Math, Science",
      city: "Ottawa",
      postal_code: "K1A 0B1",
      additional_notes: "Looking for foundational skills.",
      status: "Can't Reach",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Avery",
      parent_last_name: "Phillips",
      parent_phone: "780-555-6543",
      parent_email: "avery.phillips@example.com",
      child_first_name: "Mia",
      child_grade: "Grade 7",
      subjects_interested: "Science, Coding",
      city: "Edmonton",
      postal_code: "T5K 2N1",
      additional_notes: "Prefers hands-on coding sessions.",
      status: "Trial Scheduled",
      how_did_you_hear: "Instagram",
    },
    {
      parent_first_name: "Noah",
      parent_last_name: "Foster",
      parent_phone: "416-555-3210",
      parent_email: "noah.foster@example.com",
      child_first_name: "Liam",
      child_grade: "Grade 4",
      subjects_interested: "Math",
      city: "Toronto",
      postal_code: "M4V 2N1",
      additional_notes: "Needs help preparing for quizzes.",
      status: "No Show",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Grace",
      parent_last_name: "Jenkins",
      parent_phone: "905-555-8765",
      parent_email: "grace.jenkins@example.com",
      child_first_name: "Ella",
      child_grade: "Grade 8",
      subjects_interested: "Math, Science",
      city: "Mississauga",
      postal_code: "L5R 3N2",
      additional_notes: "Interested in advanced topics.",
      status: "Enrolled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Sophia",
      parent_last_name: "Griffin",
      parent_phone: "647-555-7890",
      parent_email: "sophia.griffin@example.com",
      child_first_name: "Noah",
      child_grade: "Grade 3",
      subjects_interested: "Science, Coding",
      city: "Toronto",
      postal_code: "M4B 1X2",
      additional_notes: "Looking for engaging lessons.",
      status: "Invoice Sent",
      how_did_you_hear: "Facebook",
    },
    {
      parent_first_name: "Mason",
      parent_last_name: "Chavez",
      parent_phone: "905-555-5432",
      parent_email: "mason.chavez@example.com",
      child_first_name: "Lucas",
      child_grade: "Grade 2",
      subjects_interested: "Math, English",
      city: "Hamilton",
      postal_code: "L8P 3L4",
      additional_notes: "Needs help with vocabulary.",
      status: "New Lead",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Emily",
      parent_last_name: "Peterson",
      parent_phone: "403-555-6789",
      parent_email: "emily.peterson@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 5",
      subjects_interested: "English",
      city: "Calgary",
      postal_code: "T2G 3N4",
      additional_notes: "Looking for reading comprehension classes.",
      status: "Trial Completed",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Ella",
      parent_last_name: "Watkins",
      parent_phone: "416-555-9876",
      parent_email: "ella.watkins@example.com",
      child_first_name: "Liam",
      child_grade: "Grade 6",
      subjects_interested: "Science, Math",
      city: "Toronto",
      postal_code: "M4G 2N4",
      additional_notes: "Needs help with test prep.",
      status: "Trial Scheduled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Ava",
      parent_last_name: "Cooper",
      parent_phone: "905-555-1234",
      parent_email: "ava.cooper@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 7",
      subjects_interested: "Math",
      city: "Mississauga",
      postal_code: "L5R 2N3",
      additional_notes: "Interested in group classes.",
      status: "Invoice Sent",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Isabella",
      parent_last_name: "Ramirez",
      parent_phone: "780-555-5432",
      parent_email: "isabella.ramirez@example.com",
      child_first_name: "Lucas",
      child_grade: "Grade 3",
      subjects_interested: "Science, English",
      city: "Edmonton",
      postal_code: "T5J 1X2",
      additional_notes: "Looking for personalized learning.",
      status: "Enrolled",
      how_did_you_hear: "Facebook Ad",
    },
    {
      parent_first_name: "Benjamin",
      parent_last_name: "Campbell",
      parent_phone: "905-555-6789",
      parent_email: "benjamin.campbell@example.com",
      child_first_name: "Ava",
      child_grade: "Grade 8",
      subjects_interested: "Math, Coding",
      city: "Brampton",
      postal_code: "L6R 2X1",
      additional_notes: "Needs flexible scheduling.",
      status: "Trial Completed",
      how_did_you_hear: "Search Engine",
    },
    {
      parent_first_name: "Mia",
      parent_last_name: "Bell",
      parent_phone: "416-555-5432",
      parent_email: "mia.bell@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 2",
      subjects_interested: "English, Science",
      city: "Toronto",
      postal_code: "M4B 1L4",
      additional_notes: "Looking for weekly sessions.",
      status: "Can't Reach",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Lucas",
      parent_last_name: "Fisher",
      parent_phone: "905-555-9876",
      parent_email: "lucas.fisher@example.com",
      child_first_name: "Ella",
      child_grade: "Grade 5",
      subjects_interested: "Math, Science",
      city: "Mississauga",
      postal_code: "L5V 1B2",
      additional_notes: "Interested in practical learning.",
      status: "Trial Scheduled",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Grace",
      parent_last_name: "Ross",
      parent_phone: "905-555-4321",
      parent_email: "grace.ross@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 4",
      subjects_interested: "English, Coding",
      city: "Hamilton",
      postal_code: "L8P 1N3",
      additional_notes: "Needs weekend sessions.",
      status: "No Show",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Avery",
      parent_last_name: "Parker",
      parent_phone: "905-555-6543",
      parent_email: "avery.parker@example.com",
      child_first_name: "Lucas",
      child_grade: "Grade 8",
      subjects_interested: "Science",
      city: "Brampton",
      postal_code: "L6X 4B1",
      additional_notes: "Looking for evening lessons.",
      status: "Enrolled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Liam",
      parent_last_name: "Howard",
      parent_phone: "780-555-1234",
      parent_email: "liam.howard@example.com",
      child_first_name: "Noah",
      child_grade: "Grade 6",
      subjects_interested: "Math, Coding",
      city: "Edmonton",
      postal_code: "T5K 1X3",
      additional_notes: "Prefers flexible schedules.",
      status: "New Lead",
      how_did_you_hear: "Instagram",
    },
    {
      parent_first_name: "Ella",
      parent_last_name: "Nelson",
      parent_phone: "905-555-7890",
      parent_email: "ella.nelson@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 7",
      subjects_interested: "Math",
      city: "Mississauga",
      postal_code: "L5R 3X1",
      additional_notes: "Needs help with advanced math.",
      status: "Invoice Sent",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "James",
      parent_last_name: "Morris",
      parent_phone: "416-555-9876",
      parent_email: "james.morris@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 8",
      subjects_interested: "Science, Math",
      city: "Toronto",
      postal_code: "M4C 1B6",
      additional_notes: "Needs help with high school preparation.",
      status: "Invoice Sent",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Sophia",
      parent_last_name: "Turner",
      parent_phone: "647-555-5432",
      parent_email: "sophia.turner@example.com",
      child_first_name: "Noah",
      child_grade: "Grade 6",
      subjects_interested: "Coding, English",
      city: "Toronto",
      postal_code: "M4B 2T3",
      additional_notes: "Prefers evening sessions.",
      status: "Trial Completed",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Oliver",
      parent_last_name: "Bell",
      parent_phone: "905-555-6789",
      parent_email: "oliver.bell@example.com",
      child_first_name: "Ava",
      child_grade: "Grade 3",
      subjects_interested: "Math, English",
      city: "Mississauga",
      postal_code: "L5B 3T2",
      additional_notes: "Needs basic foundational skills.",
      status: "New Lead",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Emily",
      parent_last_name: "Garcia",
      parent_phone: "905-555-4321",
      parent_email: "emily.garcia@example.com",
      child_first_name: "Liam",
      child_grade: "Grade 4",
      subjects_interested: "Math",
      city: "Brampton",
      postal_code: "L6T 2P4",
      additional_notes: "Looking for test preparation.",
      status: "Can't Reach",
      how_did_you_hear: "Instagram",
    },
    {
      parent_first_name: "Lucas",
      parent_last_name: "Anderson",
      parent_phone: "905-555-1234",
      parent_email: "lucas.anderson@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 5",
      subjects_interested: "Coding, Math",
      city: "Hamilton",
      postal_code: "L8P 1T3",
      additional_notes: "Prefers hands-on learning.",
      status: "Trial Scheduled",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Ava",
      parent_last_name: "Nelson",
      parent_phone: "905-555-6543",
      parent_email: "ava.nelson@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 2",
      subjects_interested: "English",
      city: "Hamilton",
      postal_code: "L8P 2N4",
      additional_notes: "Needs grammar improvement.",
      status: "No Show",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Benjamin",
      parent_last_name: "Moore",
      parent_phone: "905-555-9876",
      parent_email: "benjamin.moore@example.com",
      child_first_name: "Lucas",
      child_grade: "Grade 3",
      subjects_interested: "Science, Math",
      city: "Mississauga",
      postal_code: "L5B 4T2",
      additional_notes: "Interested in group classes.",
      status: "Enrolled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Charlotte",
      parent_last_name: "Phillips",
      parent_phone: "780-555-3210",
      parent_email: "charlotte.phillips@example.com",
      child_first_name: "Ava",
      child_grade: "Grade 6",
      subjects_interested: "Math, Science",
      city: "Edmonton",
      postal_code: "T5K 1L2",
      additional_notes: "Needs flexible scheduling.",
      status: "Invoice Sent",
      how_did_you_hear: "Search Engine",
    },
    {
      parent_first_name: "Mia",
      parent_last_name: "Scott",
      parent_phone: "613-555-8765",
      parent_email: "mia.scott@example.com",
      child_first_name: "Noah",
      child_grade: "Grade 8",
      subjects_interested: "Coding",
      city: "Ottawa",
      postal_code: "K1P 1R2",
      additional_notes: "Interested in advanced coding.",
      status: "New Lead",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Avery",
      parent_last_name: "Ramirez",
      parent_phone: "905-555-5432",
      parent_email: "avery.ramirez@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 7",
      subjects_interested: "Math",
      city: "Mississauga",
      postal_code: "L5M 3N2",
      additional_notes: "Looking for one-on-one lessons.",
      status: "Trial Completed",
      how_did_you_hear: "Facebook Ad",
    },
    {
      parent_first_name: "Ella",
      parent_last_name: "Thompson",
      parent_phone: "647-555-6789",
      parent_email: "ella.thompson@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 5",
      subjects_interested: "Math, Science",
      city: "Toronto",
      postal_code: "M4B 3L5",
      additional_notes: "Needs help with exams.",
      status: "Trial Scheduled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Noah",
      parent_last_name: "Hughes",
      parent_phone: "905-555-4321",
      parent_email: "noah.hughes@example.com",
      child_first_name: "Lucas",
      child_grade: "Grade 4",
      subjects_interested: "English",
      city: "Hamilton",
      postal_code: "L8P 1N2",
      additional_notes: "Needs creative writing support.",
      status: "Invoice Sent",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Isabella",
      parent_last_name: "Parker",
      parent_phone: "416-555-6543",
      parent_email: "isabella.parker@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 3",
      subjects_interested: "English",
      city: "Toronto",
      postal_code: "M4C 1B2",
      additional_notes: "Needs reading comprehension lessons.",
      status: "Enrolled",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Liam",
      parent_last_name: "Cooper",
      parent_phone: "905-555-7890",
      parent_email: "liam.cooper@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 7",
      subjects_interested: "Math, Science",
      city: "Mississauga",
      postal_code: "L5B 2L4",
      additional_notes: "Prefers evening sessions.",
      status: "Trial Completed",
      how_did_you_hear: "Search Engine",
    },
    {
      parent_first_name: "Emily",
      parent_last_name: "Adams",
      parent_phone: "905-555-8765",
      parent_email: "emily.adams@example.com",
      child_first_name: "Ava",
      child_grade: "Grade 8",
      subjects_interested: "Science",
      city: "Brampton",
      postal_code: "L6X 4N1",
      additional_notes: "Looking for exam preparation.",
      status: "Can't Reach",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Lucas",
      parent_last_name: "Martinez",
      parent_phone: "780-555-3210",
      parent_email: "lucas.martinez@example.com",
      child_first_name: "Liam",
      child_grade: "Grade 2",
      subjects_interested: "English, Math",
      city: "Edmonton",
      postal_code: "T5J 1N3",
      additional_notes: "Needs help with reading fluency.",
      status: "Trial Scheduled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Sophia",
      parent_last_name: "Roberts",
      parent_phone: "905-555-9876",
      parent_email: "sophia.roberts@example.com",
      child_first_name: "Ella",
      child_grade: "Grade 4",
      subjects_interested: "Math",
      city: "Mississauga",
      postal_code: "L5B 1N3",
      additional_notes: "Wants personalized attention.",
      status: "No Show",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Ava",
      parent_last_name: "Foster",
      parent_phone: "905-555-5432",
      parent_email: "ava.foster@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 6",
      subjects_interested: "Coding, Math",
      city: "Brampton",
      postal_code: "L6R 1X3",
      additional_notes: "Needs weekend sessions.",
      status: "Enrolled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Grace",
      parent_last_name: "Peterson",
      parent_phone: "905-555-3210",
      parent_email: "grace.peterson@example.com",
      child_first_name: "Noah",
      child_grade: "Grade 7",
      subjects_interested: "Science",
      city: "Hamilton",
      postal_code: "L8P 3L4",
      additional_notes: "Needs tutoring in chemistry.",
      status: "New Lead",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Ella",
      parent_last_name: "Bell",
      parent_phone: "905-555-6543",
      parent_email: "ella.bell@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 2",
      subjects_interested: "English",
      city: "Hamilton",
      postal_code: "L8P 1B4",
      additional_notes: "Looking for weekday lessons.",
      status: "Invoice Sent",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Michael",
      parent_last_name: "Henderson",
      parent_phone: "403-555-1234",
      parent_email: "michael.henderson@example.com",
      child_first_name: "Liam",
      child_grade: "Grade 6",
      subjects_interested: "Math, Coding",
      city: "Calgary",
      postal_code: "T2P 1B3",
      additional_notes: "Interested in hands-on coding projects.",
      status: "Invoice Sent",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Sophia",
      parent_last_name: "Martinez",
      parent_phone: "514-555-9876",
      parent_email: "sophia.martinez@example.com",
      child_first_name: "Noah",
      child_grade: "Grade 5",
      subjects_interested: "English, Math",
      city: "Montreal",
      postal_code: "H2X 3L2",
      additional_notes: "Needs help with advanced reading comprehension.",
      status: "Trial Completed",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Ethan",
      parent_last_name: "Roberts",
      parent_phone: "604-555-6543",
      parent_email: "ethan.roberts@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 3",
      subjects_interested: "Science, English",
      city: "Vancouver",
      postal_code: "V6B 2L1",
      additional_notes: "Prefers weekend sessions.",
      status: "New Lead",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Grace",
      parent_last_name: "Parker",
      parent_phone: "647-555-6789",
      parent_email: "grace.parker@example.com",
      child_first_name: "Ella",
      child_grade: "Grade 4",
      subjects_interested: "Math, Science",
      city: "Toronto",
      postal_code: "M4V 2N3",
      additional_notes: "Needs evening lessons.",
      status: "Can't Reach",
      how_did_you_hear: "Instagram",
    },
    {
      parent_first_name: "Isabella",
      parent_last_name: "Bell",
      parent_phone: "905-555-5432",
      parent_email: "isabella.bell@example.com",
      child_first_name: "Lucas",
      child_grade: "Grade 2",
      subjects_interested: "English, Math",
      city: "Mississauga",
      postal_code: "L5B 1N4",
      additional_notes: "Looking for one-on-one sessions.",
      status: "Trial Scheduled",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Charlotte",
      parent_last_name: "Griffin",
      parent_phone: "905-555-3210",
      parent_email: "charlotte.griffin@example.com",
      child_first_name: "Mason",
      child_grade: "Grade 6",
      subjects_interested: "Math, Coding",
      city: "Hamilton",
      postal_code: "L8P 3N2",
      additional_notes: "Needs preparation for math competitions.",
      status: "No Show",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Lucas",
      parent_last_name: "Brown",
      parent_phone: "416-555-6543",
      parent_email: "lucas.brown@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 7",
      subjects_interested: "English, Science",
      city: "Toronto",
      postal_code: "M4B 1L4",
      additional_notes: "Wants creative writing support.",
      status: "Enrolled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Emma",
      parent_last_name: "Foster",
      parent_phone: "613-555-7890",
      parent_email: "emma.foster@example.com",
      child_first_name: "Liam",
      child_grade: "Grade 5",
      subjects_interested: "Math, Coding",
      city: "Ottawa",
      postal_code: "K1A 1N3",
      additional_notes: "Needs foundational math support.",
      status: "Invoice Sent",
      how_did_you_hear: "Search Engine",
    },
    {
      parent_first_name: "Mia",
      parent_last_name: "Hughes",
      parent_phone: "780-555-4321",
      parent_email: "mia.hughes@example.com",
      child_first_name: "Ava",
      child_grade: "Grade 8",
      subjects_interested: "Coding",
      city: "Edmonton",
      postal_code: "T5K 2N1",
      additional_notes: "Looking for advanced coding lessons.",
      status: "New Lead",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Ella",
      parent_last_name: "Reed",
      parent_phone: "905-555-5432",
      parent_email: "ella.reed@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 6",
      subjects_interested: "English",
      city: "Mississauga",
      postal_code: "L5M 1N4",
      additional_notes: "Needs help with essays.",
      status: "Trial Completed",
      how_did_you_hear: "Facebook",
    },
    {
      parent_first_name: "Benjamin",
      parent_last_name: "Scott",
      parent_phone: "905-555-8765",
      parent_email: "benjamin.scott@example.com",
      child_first_name: "Ella",
      child_grade: "Grade 4",
      subjects_interested: "Math",
      city: "Hamilton",
      postal_code: "L8P 1N3",
      additional_notes: "Needs foundational math lessons.",
      status: "Trial Scheduled",
      how_did_you_hear: "Instagram",
    },
    {
      parent_first_name: "Liam",
      parent_last_name: "Thompson",
      parent_phone: "647-555-5432",
      parent_email: "liam.thompson@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 5",
      subjects_interested: "Math, Science",
      city: "Toronto",
      postal_code: "M4V 2N1",
      additional_notes: "Needs evening classes.",
      status: "Invoice Sent",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Olivia",
      parent_last_name: "Williams",
      parent_phone: "905-555-6543",
      parent_email: "olivia.williams@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 7",
      subjects_interested: "Science, Coding",
      city: "Mississauga",
      postal_code: "L5B 1N3",
      additional_notes: "Looking for group classes.",
      status: "Enrolled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Avery",
      parent_last_name: "Howard",
      parent_phone: "905-555-1234",
      parent_email: "avery.howard@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 8",
      subjects_interested: "English, Science",
      city: "Brampton",
      postal_code: "L6T 3N2",
      additional_notes: "Interested in test prep support.",
      status: "Trial Completed",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Isabella",
      parent_last_name: "Moore",
      parent_phone: "613-555-9876",
      parent_email: "isabella.moore@example.com",
      child_first_name: "Lucas",
      child_grade: "Grade 3",
      subjects_interested: "Math",
      city: "Ottawa",
      postal_code: "K1A 1X4",
      additional_notes: "Needs help with multiplication tables.",
      status: "Can't Reach",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Grace",
      parent_last_name: "Adams",
      parent_phone: "905-555-7890",
      parent_email: "grace.adams@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 6",
      subjects_interested: "Math, English",
      city: "Mississauga",
      postal_code: "L5M 2N4",
      additional_notes: "Looking for weekday evening classes.",
      status: "Trial Scheduled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Noah",
      parent_last_name: "Evans",
      parent_phone: "905-555-5432",
      parent_email: "noah.evans@example.com",
      child_first_name: "Liam",
      child_grade: "Grade 5",
      subjects_interested: "English",
      city: "Hamilton",
      postal_code: "L8P 3N4",
      additional_notes: "Needs creative writing improvement.",
      status: "No Show",
      how_did_you_hear: "Instagram",
    },
    {
      parent_first_name: "Ella",
      parent_last_name: "Martinez",
      parent_phone: "905-555-4321",
      parent_email: "ella.martinez@example.com",
      child_first_name: "Ava",
      child_grade: "Grade 2",
      subjects_interested: "English, Math",
      city: "Hamilton",
      postal_code: "L8P 1N2",
      additional_notes: "Looking for one-on-one sessions.",
      status: "Enrolled",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Mason",
      parent_last_name: "King",
      parent_phone: "905-555-9876",
      parent_email: "mason.king@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 7",
      subjects_interested: "Science, Math",
      city: "Brampton",
      postal_code: "L6R 3L1",
      additional_notes: "Wants preparation for school exams.",
      status: "New Lead",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Sophia",
      parent_last_name: "Brown",
      parent_phone: "416-555-6789",
      parent_email: "sophia.brown@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 3",
      subjects_interested: "Science",
      city: "Toronto",
      postal_code: "M4B 2L3",
      additional_notes: "Needs help with science projects.",
      status: "Invoice Sent",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Oliver",
      parent_last_name: "Bennett",
      parent_phone: "780-555-1234",
      parent_email: "oliver.bennett@example.com",
      child_first_name: "Liam",
      child_grade: "Grade 7",
      subjects_interested: "Math, Coding",
      city: "Edmonton",
      postal_code: "T5J 2N3",
      additional_notes: "Prefers evening lessons.",
      status: "Invoice Sent",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Sophia",
      parent_last_name: "Green",
      parent_phone: "905-555-5432",
      parent_email: "sophia.green@example.com",
      child_first_name: "Ella",
      child_grade: "Grade 4",
      subjects_interested: "Science, English",
      city: "Mississauga",
      postal_code: "L5M 2R4",
      additional_notes: "Needs help with reading comprehension.",
      status: "Trial Completed",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Charlotte",
      parent_last_name: "Harris",
      parent_phone: "416-555-6789",
      parent_email: "charlotte.harris@example.com",
      child_first_name: "Noah",
      child_grade: "Grade 3",
      subjects_interested: "Math, Science",
      city: "Toronto",
      postal_code: "M4V 1N4",
      additional_notes: "Interested in foundational skills.",
      status: "New Lead",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Ava",
      parent_last_name: "Walker",
      parent_phone: "613-555-9876",
      parent_email: "ava.walker@example.com",
      child_first_name: "Lucas",
      child_grade: "Grade 6",
      subjects_interested: "Coding",
      city: "Ottawa",
      postal_code: "K1P 1L2",
      additional_notes: "Wants to learn coding basics.",
      status: "Can't Reach",
      how_did_you_hear: "Facebook Ad",
    },
    {
      parent_first_name: "Mason",
      parent_last_name: "Young",
      parent_phone: "905-555-1234",
      parent_email: "mason.young@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 8",
      subjects_interested: "Math, Science",
      city: "Brampton",
      postal_code: "L6T 3R5",
      additional_notes: "Looking for advanced lessons.",
      status: "Trial Scheduled",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Liam",
      parent_last_name: "Clark",
      parent_phone: "905-555-7890",
      parent_email: "liam.clark@example.com",
      child_first_name: "Ava",
      child_grade: "Grade 5",
      subjects_interested: "English, Coding",
      city: "Hamilton",
      postal_code: "L8P 1N3",
      additional_notes: "Prefers one-on-one sessions.",
      status: "No Show",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Isabella",
      parent_last_name: "Smith",
      parent_phone: "905-555-5432",
      parent_email: "isabella.smith@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 7",
      subjects_interested: "Science",
      city: "Mississauga",
      postal_code: "L5B 1N2",
      additional_notes: "Needs help with test prep.",
      status: "Enrolled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Ella",
      parent_last_name: "Brown",
      parent_phone: "905-555-6543",
      parent_email: "ella.brown@example.com",
      child_first_name: "Liam",
      child_grade: "Grade 6",
      subjects_interested: "Math, Science",
      city: "Mississauga",
      postal_code: "L5M 2N3",
      additional_notes: "Needs flexible scheduling.",
      status: "Invoice Sent",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Benjamin",
      parent_last_name: "Evans",
      parent_phone: "905-555-9876",
      parent_email: "benjamin.evans@example.com",
      child_first_name: "Ava",
      child_grade: "Grade 8",
      subjects_interested: "English, Science",
      city: "Mississauga",
      postal_code: "L5B 2N4",
      additional_notes: "Interested in evening classes.",
      status: "New Lead",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Emily",
      parent_last_name: "Martinez",
      parent_phone: "905-555-8765",
      parent_email: "emily.martinez@example.com",
      child_first_name: "Noah",
      child_grade: "Grade 3",
      subjects_interested: "Science",
      city: "Hamilton",
      postal_code: "L8P 3T4",
      additional_notes: "Wants help with projects.",
      status: "Trial Completed",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Grace",
      parent_last_name: "King",
      parent_phone: "905-555-1234",
      parent_email: "grace.king@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 5",
      subjects_interested: "Math, Science",
      city: "Toronto",
      postal_code: "M4C 2N4",
      additional_notes: "Looking for test prep.",
      status: "Trial Scheduled",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Lucas",
      parent_last_name: "Parker",
      parent_phone: "905-555-5432",
      parent_email: "lucas.parker@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 7",
      subjects_interested: "English",
      city: "Mississauga",
      postal_code: "L5R 2N3",
      additional_notes: "Prefers one-on-one tutoring.",
      status: "Invoice Sent",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Charlotte",
      parent_last_name: "Anderson",
      parent_phone: "905-555-6789",
      parent_email: "charlotte.anderson@example.com",
      child_first_name: "Ella",
      child_grade: "Grade 4",
      subjects_interested: "Math, Coding",
      city: "Brampton",
      postal_code: "L6T 3N3",
      additional_notes: "Looking for weekend classes.",
      status: "Enrolled",
      how_did_you_hear: "Facebook Ad",
    },
    {
      parent_first_name: "Mia",
      parent_last_name: "Scott",
      parent_phone: "905-555-7890",
      parent_email: "mia.scott@example.com",
      child_first_name: "Liam",
      child_grade: "Grade 6",
      subjects_interested: "Math, Science",
      city: "Mississauga",
      postal_code: "L5B 1N3",
      additional_notes: "Needs flexible scheduling.",
      status: "Trial Completed",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Sophia",
      parent_last_name: "Thompson",
      parent_phone: "905-555-9876",
      parent_email: "sophia.thompson@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 7",
      subjects_interested: "Coding",
      city: "Mississauga",
      postal_code: "L5M 2N2",
      additional_notes: "Interested in advanced coding lessons.",
      status: "Trial Scheduled",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Noah",
      parent_last_name: "Hughes",
      parent_phone: "905-555-6543",
      parent_email: "noah.hughes@example.com",
      child_first_name: "Sophia",
      child_grade: "Grade 8",
      subjects_interested: "Science, Math",
      city: "Hamilton",
      postal_code: "L8P 2T3",
      additional_notes: "Prefers hands-on lessons.",
      status: "No Show",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Isabella",
      parent_last_name: "Moore",
      parent_phone: "905-555-5432",
      parent_email: "isabella.moore@example.com",
      child_first_name: "Lucas",
      child_grade: "Grade 3",
      subjects_interested: "Math",
      city: "Brampton",
      postal_code: "L6T 3N4",
      additional_notes: "Needs help with homework.",
      status: "Enrolled",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Liam",
      parent_last_name: "Foster",
      parent_phone: "905-555-4321",
      parent_email: "liam.foster@example.com",
      child_first_name: "Ella",
      child_grade: "Grade 6",
      subjects_interested: "Math, English",
      city: "Toronto",
      postal_code: "M4C 2T4",
      additional_notes: "Wants improvement in writing skills.",
      status: "New Lead",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Emily",
      parent_last_name: "White",
      parent_phone: "905-555-1234",
      parent_email: "emily.white@example.com",
      child_first_name: "Ava",
      child_grade: "Grade 5",
      subjects_interested: "Science, Math",
      city: "Mississauga",
      postal_code: "L5R 2T3",
      additional_notes: "Needs help with final exams.",
      status: "Invoice Sent",
      how_did_you_hear: "Flyer",
    },
  ]);
}
