/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex("clients").del();
  await knex("clients").insert([
    {
      parent_first_name: "Kenneth",
      parent_last_name: "Nelson",
      parent_phone: "480-300-0488",
      parent_email: "kenneth.nelson@example.com",
      child_first_name: "Max",
      child_grade: "Grade 8",
      subjects_interested: "English, Coding, Science, Math",
      city: "Hamilton",
      postal_code: "77830",
      additional_notes: "Collection will able card fly really.",
      status: "Trial Completed",
      how_did_you_hear: "Social Media",
    },
    {
      parent_first_name: "James",
      parent_last_name: "Long",
      parent_phone: "738-148-0098",
      parent_email: "james.long@example.com",
      child_first_name: "Mario",
      child_grade: "Grade 4",
      subjects_interested: "Math, Coding, Science",
      city: "Brampton",
      postal_code: "84246",
      additional_notes: "May how direction community.",
      status: "Trial Completed",
      how_did_you_hear: "Online Ad",
    },
    {
      parent_first_name: "Donald",
      parent_last_name: "Cohen",
      parent_phone: "114-168-7954",
      parent_email: "donald.cohen@example.com",
      child_first_name: "Richard",
      child_grade: "Grade 8",
      subjects_interested: "English, Coding",
      city: "Toronto",
      postal_code: "76831",
      additional_notes:
        "Media election statement behavior consider air without.",
      status: "Invoice Sent",
      how_did_you_hear: "Online Ad",
    },
    {
      parent_first_name: "Monique",
      parent_last_name: "Miller",
      parent_phone: "434-795-3528",
      parent_email: "monique.miller@example.com",
      child_first_name: "Alexander",
      child_grade: "Grade 5",
      subjects_interested: "Coding",
      city: "Toronto",
      postal_code: "30253",
      additional_notes:
        "Call action reality traditional property everything partner.",
      status: "Can't Reach",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Breanna",
      parent_last_name: "Ward",
      parent_phone: "021-701-0664",
      parent_email: "breanna.ward@example.com",
      child_first_name: "Madison",
      child_grade: "Grade 5",
      subjects_interested: "Math, Science, English",
      city: "London",
      postal_code: "15129",
      additional_notes: "Forward clearly think traditional.",
      status: "Not a Fit",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Jesse",
      parent_last_name: "Evans",
      parent_phone: "578-511-8270",
      parent_email: "jesse.evans@example.com",
      child_first_name: "Heather",
      child_grade: "Grade 2",
      subjects_interested: "Science, English",
      city: "Ottawa",
      postal_code: "20502",
      additional_notes: "That energy hold.",
      status: "Can't Reach",
      how_did_you_hear: "Friend Referral",
    },
    {
      parent_first_name: "Ricky",
      parent_last_name: "Vaughn",
      parent_phone: "560-653-7605",
      parent_email: "ricky.vaughn@example.com",
      child_first_name: "Stacy",
      child_grade: "Grade 1",
      subjects_interested: "Coding, Science, English, Math",
      city: "Hamilton",
      postal_code: "61535",
      additional_notes: "Her small reduce thousand keep.",
      status: "Invoice Sent",
      how_did_you_hear: "Online Ad",
    },
    {
      parent_first_name: "Joseph",
      parent_last_name: "Hernandez",
      parent_phone: "163-582-7453",
      parent_email: "joseph.hernandez@example.com",
      child_first_name: "Tamara",
      child_grade: "Grade 4",
      subjects_interested: "English, Coding, Math, Science",
      city: "Brampton",
      postal_code: "65244",
      additional_notes:
        "Production whatever difficult though former discussion.",
      status: "Not a Fit",
      how_did_you_hear: "Online Ad",
    },
    {
      parent_first_name: "April",
      parent_last_name: "Wilson",
      parent_phone: "074-526-4410",
      parent_email: "april.wilson@example.com",
      child_first_name: "Deborah",
      child_grade: "Grade 5",
      subjects_interested: "Coding, English, Science",
      city: "Markham",
      postal_code: "36932",
      additional_notes: "Involve run single our he.",
      status: "Invoice Sent",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Joel",
      parent_last_name: "Baldwin",
      parent_phone: "424-552-2545",
      parent_email: "joel.baldwin@example.com",
      child_first_name: "Sharon",
      child_grade: "Grade 6",
      subjects_interested: "English, Coding, Math",
      city: "Windsor",
      postal_code: "57910",
      additional_notes: "Heart beat security difference difficult probably.",
      status: "Not a Fit",
      how_did_you_hear: "Social Media",
    },
    {
      parent_first_name: "Jacob",
      parent_last_name: "Bartlett",
      parent_phone: "556-795-2938",
      parent_email: "jacob.bartlett@example.com",
      child_first_name: "Jacqueline",
      child_grade: "Grade 8",
      subjects_interested: "Coding, Math, English, Science",
      city: "Markham",
      postal_code: "72382",
      additional_notes: "Study leg professional area blue hope.",
      status: "No Show",
      how_did_you_hear: "Social Media",
    },
    {
      parent_first_name: "Breanna",
      parent_last_name: "Lopez",
      parent_phone: "325-655-8932",
      parent_email: "breanna.lopez@example.com",
      child_first_name: "Danielle",
      child_grade: "Grade 6",
      subjects_interested: "English, Coding, Math, Science",
      city: "Markham",
      postal_code: "54705",
      additional_notes:
        "Either statement attorney land exist civil listen catch.",
      status: "Not a Fit",
      how_did_you_hear: "Online Ad",
    },
    {
      parent_first_name: "Diana",
      parent_last_name: "Romero",
      parent_phone: "761-290-9555",
      parent_email: "diana.romero@example.com",
      child_first_name: "Kristy",
      child_grade: "Grade 3",
      subjects_interested: "Science, Math, Coding",
      city: "Ottawa",
      postal_code: "62243",
      additional_notes: "Western sell study he court.",
      status: "Not a Fit",
      how_did_you_hear: "Friend Referral",
    },
    {
      parent_first_name: "Hayden",
      parent_last_name: "Sampson",
      parent_phone: "704-156-1484",
      parent_email: "hayden.sampson@example.com",
      child_first_name: "Susan",
      child_grade: "Grade 7",
      subjects_interested: "Coding, Science, English",
      city: "Ottawa",
      postal_code: "34462",
      additional_notes: "Case begin audience whose after.",
      status: "Invoice Sent",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Ryan",
      parent_last_name: "Cruz",
      parent_phone: "250-173-7433",
      parent_email: "ryan.cruz@example.com",
      child_first_name: "Stephen",
      child_grade: "Grade 4",
      subjects_interested: "Math",
      city: "Brampton",
      postal_code: "64121",
      additional_notes: "Nearly record tax sport unit.",
      status: "Trial Completed",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Thomas",
      parent_last_name: "Lee",
      parent_phone: "289-291-8591",
      parent_email: "thomas.lee@example.com",
      child_first_name: "Cynthia",
      child_grade: "Grade 5",
      subjects_interested: "Science, English, Coding, Math",
      city: "Ottawa",
      postal_code: "80082",
      additional_notes: "Even maintain Democrat still.",
      status: "Trial Scheduled",
      how_did_you_hear: "Online Ad",
    },
    {
      parent_first_name: "Hayden",
      parent_last_name: "Sampson",
      parent_phone: "704-156-1484",
      parent_email: "hayden.sampson@example.com",
      child_first_name: "Susan",
      child_grade: "Grade 7",
      subjects_interested: "Coding, Science, English",
      city: "Ottawa",
      postal_code: "34462",
      additional_notes: "Case begin audience whose after.",
      status: "Invoice Sent",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Ryan",
      parent_last_name: "Cruz",
      parent_phone: "250-173-7433",
      parent_email: "ryan.cruz@example.com",
      child_first_name: "Stephen",
      child_grade: "Grade 4",
      subjects_interested: "Math",
      city: "Brampton",
      postal_code: "64121",
      additional_notes: "Nearly record tax sport unit.",
      status: "Trial Completed",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Thomas",
      parent_last_name: "Lee",
      parent_phone: "289-291-8591",
      parent_email: "thomas.lee@example.com",
      child_first_name: "Cynthia",
      child_grade: "Grade 5",
      subjects_interested: "Science, English, Coding, Math",
      city: "Ottawa",
      postal_code: "80082",
      additional_notes: "Even maintain Democrat still.",
      status: "Trial Scheduled",
      how_did_you_hear: "Online Ad",
    },
    {
      parent_first_name: "Amanda",
      parent_last_name: "Smith",
      parent_phone: "123-456-7890",
      parent_email: "amanda.smith@example.com",
      child_first_name: "Lucas",
      child_grade: "Grade 3",
      subjects_interested: "Math",
      city: "Mississauga",
      postal_code: "N5Z 2P8",
      additional_notes: "Interested in group classes.",
      status: "Form Submitted",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "John",
      parent_last_name: "Doe",
      parent_phone: "987-654-3210",
      parent_email: "john.doe@example.com",
      child_first_name: "Emma",
      child_grade: "Grade 6",
      subjects_interested: "Science, Math",
      city: "Toronto",
      postal_code: "M4B 1B3",
      additional_notes: "Needs evening sessions.",
      status: "Can't Reach",
      how_did_you_hear: "Social Media",
    },
    {
      parent_first_name: "Sarah",
      parent_last_name: "Brown",
      parent_phone: "345-678-9012",
      parent_email: "sarah.brown@gmail.com",
      child_first_name: "Ella",
      child_grade: "Grade 2",
      subjects_interested: "English",
      city: "Hamilton",
      postal_code: "L8P 1B2",
      additional_notes: "Prefers one-on-one tutoring.",
      status: "Not a Fit",
      how_did_you_hear: "Online Search",
    },
    {
      parent_first_name: "Liam",
      parent_last_name: "Walker",
      parent_phone: "234-567-8901",
      parent_email: "liam.walker@outlook.com",
      child_first_name: "Ethan",
      child_grade: "Grade 7",
      subjects_interested: "Math, Coding",
      city: "Ottawa",
      postal_code: "K1A 0B1",
      additional_notes: "Looking for immediate start.",
      status: "Invoice Sent",
      how_did_you_hear: "Flyer",
    },
    {
      parent_first_name: "Olivia",
      parent_last_name: "Taylor",
      parent_phone: "876-543-2109",
      parent_email: "olivia.taylor@yahoo.com",
      child_first_name: "Chloe",
      child_grade: "Grade 4",
      subjects_interested: "Science, Math, English",
      city: "Brampton",
      postal_code: "L6T 3R1",
      additional_notes: "Flexible with scheduling.",
      status: "Enrolled",
      how_did_you_hear: "Referral",
    },
    {
      parent_first_name: "Emma",
      parent_last_name: "Clark",
      parent_phone: "564-738-2019",
      parent_email: "emma.clark@gmail.com",
      child_first_name: "Noah",
      child_grade: "Grade 5",
      subjects_interested: "English",
      city: "Mississauga",
      postal_code: "N5Z 2P8",
      additional_notes: "Interested in group classes.",
      status: "Trial Scheduled",
      how_did_you_hear: "Word of Mouth",
    },
    {
      parent_first_name: "Ethan",
      parent_last_name: "Hill",
      parent_phone: "908-765-4321",
      parent_email: "ethan.hill@example.com",
      child_first_name: "Ava",
      child_grade: "Grade 1",
      subjects_interested: "Coding",
      city: "Toronto",
      postal_code: "M4B 1B3",
      additional_notes: "Needs weekend sessions.",
      status: "Trial Completed",
      how_did_you_hear: "Social Media",
    },
    {
      parent_first_name: "Sophia",
      parent_last_name: "Johnson",
      parent_phone: "234-987-6543",
      parent_email: "sophia.johnson@gmail.com",
      child_first_name: "Mason",
      child_grade: "Grade 8",
      subjects_interested: "Science, Coding",
      city: "Hamilton",
      postal_code: "L8P 1B2",
      additional_notes: "Prefers evening tutoring.",
      status: "No Show",
      how_did_you_hear: "Online Search",
    },
    {
      parent_first_name: "John",
      parent_last_name: "Evans",
      parent_phone: "234-917-6543",
      parent_email: "john.evans@gmail.com",
      child_first_name: "Samuel",
      child_grade: "Grade 3",
      subjects_interested: "Science, Coding",
      city: "Hamilton",
      postal_code: "L8P 1F2",
      additional_notes: "Prefers weekend tutoring.",
      status: "Form Submitted",
      how_did_you_hear: "Online Search",
    },
    {
      parent_first_name: "Pasha",
      parent_last_name: "Samuels",
      parent_phone: "564-917-6543",
      parent_email: "Pasha.Samuels@gmail.com",
      child_first_name: "Justin",
      child_grade: "Grade 4",
      subjects_interested: "English, Coding",
      city: "Vaughan",
      postal_code: "L8P 3F2",
      additional_notes: "Prefers weekday tutoring.",
      status: "Form Submitted",
      how_did_you_hear: "Google",
    },
    {
      parent_first_name: "Michal",
      parent_last_name: "Manoah",
      parent_phone: "564-123-6543",
      parent_email: "Michal.Manoah@gmail.com",
      child_first_name: "Nikki",
      child_grade: "Grade 2",
      subjects_interested: "English",
      city: "Maple",
      postal_code: "L1P 3F2",
      additional_notes: "Prefers weekday tutoring.",
      status: "Enrolled",
      how_did_you_hear: "Facebook",
    },
  ]);
}
